//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
        public string ImgDir { get; set; }
        public Nullable<int> Existencias { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Categorias Categorias { get; set; }

        public Productos(string id,string nombre,double precio,string imgpath,int stock, int categoriaid)
        {
            ID = id;
            Nombre = nombre;
            PrecioUnitario = precio;
            ImgDir = imgpath;
            Existencias = stock;
            IDCategoria = categoriaid;
    
        }
        public Productos()
        {

        }
    }
}
